#!/usr/bin/env python3
"""
estimate_protein_radius.py

Estimates the radius of a protein from a PDB file by treating it as a sphere.

Three complementary methods are used:
  1. Radius of Gyration (Rg) — mass-weighted RMS distance from the centroid.
     Good for flexible/elongated proteins; underestimates the enclosing sphere.
  2. Hydrodynamic / equivalent sphere radius — derived from the solvent-accessible
     volume estimate: R_h = (3V / 4π)^(1/3). Useful for comparing with DLS data.
  3. Maximum extent radius (R_max) — half the longest atom–atom distance.
     A hard upper bound on the enclosing sphere.

Usage:
    python estimate_protein_radius.py <file.pdb> [--chain A] [--no-hetatm]

Requirements:
    pip install numpy biopython

Author: generated by Claude
"""

import argparse
import sys
import warnings
import numpy as np

try:
    from Bio import BiopythonWarning
    from Bio.PDB import PDBParser
except ImportError:
    sys.exit(
        "BioPython is required. Install it with:\n"
        "  pip install biopython\n"
    )

# Van der Waals radii (Å) by element symbol — used for volume estimate
VDW_RADII = {
    "H": 1.20, "C": 1.70, "N": 1.55, "O": 1.52, "S": 1.80,
    "P": 1.80, "FE": 1.80, "ZN": 1.39, "CA": 1.74, "MG": 1.73,
    "CL": 1.75, "NA": 2.27, "K":  2.75, "SE": 1.90, "BR": 1.85,
}
DEFAULT_VDW = 1.70  # fallback for unknown elements


def parse_args():
    p = argparse.ArgumentParser(
        description="Estimate protein radius from a PDB file (sphere approximation)."
    )
    p.add_argument("pdb_file", help="Path to the input PDB file")
    p.add_argument(
        "--chain", default=None,
        help="Restrict analysis to a single chain (e.g. A). Default: all chains."
    )
    p.add_argument(
        "--no-hetatm", action="store_true",
        help="Exclude HETATM records (ligands, water, etc.). Default: include them."
    )
    p.add_argument(
        "--model", type=int, default=0,
        help="Model index to use for NMR/multi-model files (0-based). Default: 0."
    )
    return p.parse_args()


def load_atoms(pdb_file, chain_id=None, exclude_hetatm=False, model_index=0):
    """Parse the PDB and return arrays of coordinates and element symbols."""
    warnings.filterwarnings("ignore", category=BiopythonWarning)
    parser = PDBParser(QUIET=True)
    structure = parser.get_structure("protein", pdb_file)

    models = list(structure.get_models())
    if model_index >= len(models):
        sys.exit(
            f"Model index {model_index} out of range "
            f"(file has {len(models)} model(s))."
        )
    model = models[model_index]

    coords = []
    elements = []

    for chain in model:
        if chain_id and chain.id != chain_id:
            continue
        for residue in chain:
            # hetfield: ' ' = standard, 'W' = water, 'H_xxx' = ligand
            hetfield = residue.id[0]
            if exclude_hetatm and hetfield != " ":
                continue
            for atom in residue:
                coords.append(atom.get_vector().get_array())
                elem = (atom.element or atom.get_name()[0]).strip().upper()
                elements.append(elem)

    if not coords:
        sys.exit(
            "No atoms found with the current filters. "
            "Check --chain and --no-hetatm options."
        )

    return np.array(coords, dtype=float), elements


def radius_of_gyration(coords):
    """
    Rg = sqrt( mean of squared distances from centroid ).
    All atoms treated as having equal mass (unweighted).
    """
    centroid = coords.mean(axis=0)
    sq_dist = np.sum((coords - centroid) ** 2, axis=1)
    return float(np.sqrt(sq_dist.mean())), centroid


def hydrodynamic_radius(coords, elements):
    """
    Estimate the equivalent sphere radius from the sum of atomic volumes.
    V_total = Σ (4/3 π r_vdw³)  — atoms treated as non-overlapping spheres.
    R_h = (3 V_total / 4π)^(1/3)
    This intentionally over-estimates volume but scales correctly.
    """
    total_volume = 0.0
    for elem in elements:
        r = VDW_RADII.get(elem, DEFAULT_VDW)
        total_volume += (4.0 / 3.0) * np.pi * r ** 3
    r_h = (3.0 * total_volume / (4.0 * np.pi)) ** (1.0 / 3.0)
    return float(r_h), total_volume


def max_extent_radius(coords):
    """
    R_max = half the maximum pairwise distance between any two atoms.
    Computed efficiently via the bounding-box diagonal as a fast upper bound,
    then an exact pairwise search on corner-candidate atoms.
    """
    # Exact O(n^2) for modest proteins; fine up to ~50 k atoms
    n = len(coords)
    if n > 20_000:
        # Use random subsample for very large structures (approximate)
        idx = np.random.choice(n, 5000, replace=False)
        sub = coords[idx]
        warnings.warn(
            f"Large structure ({n} atoms): R_max estimated from 5 000 random atoms.",
            stacklevel=2,
        )
    else:
        sub = coords

    # Vectorised pairwise distances via broadcasting on chunks
    chunk = 500
    max_sq = 0.0
    for i in range(0, len(sub), chunk):
        diff = sub[i:i+chunk, np.newaxis, :] - sub[np.newaxis, :, :]
        sq = np.sum(diff ** 2, axis=-1)
        max_sq = max(max_sq, sq.max())

    return float(np.sqrt(max_sq) / 2.0)


def print_results(pdb_file, n_atoms, chain_id, rg, centroid, r_h, total_vol, r_max):
    sep = "─" * 60
    print(sep)
    print(f"  Protein radius estimation")
    print(sep)
    print(f"  File     : {pdb_file}")
    print(f"  Chain(s) : {'all' if chain_id is None else chain_id}")
    print(f"  Atoms    : {n_atoms:,}")
    print(f"  Centroid : ({centroid[0]:.2f}, {centroid[1]:.2f}, {centroid[2]:.2f}) Å")
    print(sep)
    print(f"  Method 1 — Radius of gyration (Rg)")
    print(f"             {rg:.2f} Å")
    print(f"             Interpretation: RMS spread of atoms around the centre.")
    print()
    print(f"  Method 2 — Equivalent sphere radius (from atomic volumes)")
    print(f"             {r_h:.2f} Å   (total VdW volume: {total_vol/1000:.1f} ų × 10³)")
    print(f"             Interpretation: radius of sphere with same total VdW volume.")
    print()
    print(f"  Method 3 — Maximum extent radius (R_max = d_max / 2)")
    print(f"             {r_max:.2f} Å")
    print(f"             Interpretation: hard upper bound; half the longest dimension.")
    print(sep)
    print("  Rule of thumb: Rg ≈ 0.77 × R_max for a uniform sphere.")
    print(f"  Observed ratio Rg/R_max = {rg/r_max:.2f}")
    print(sep)


def main():
    args = parse_args()

    coords, elements = load_atoms(
        args.pdb_file,
        chain_id=args.chain,
        exclude_hetatm=args.no_hetatm,
        model_index=args.model,
    )

    rg, centroid = radius_of_gyration(coords)
    r_h, total_vol = hydrodynamic_radius(coords, elements)
    r_max = max_extent_radius(coords)

    print_results(
        pdb_file=args.pdb_file,
        n_atoms=len(coords),
        chain_id=args.chain,
        rg=rg,
        centroid=centroid,
        r_h=r_h,
        total_vol=total_vol,
        r_max=r_max,
    )


if __name__ == "__main__":
    main()